# Generated by Django 5.0.1 on 2025-11-29 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('auth_url', models.URLField(help_text='Keystone Auth URL')),
                ('project_domain_name', models.CharField(default='Default', max_length=50)),
                ('user_domain_name', models.CharField(default='Default', max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(default='RegionOne', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('idrac_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('state', models.CharField(default='up', max_length=20)),
                ('status', models.CharField(default='enabled', max_length=20)),
                ('cpu_count', models.IntegerField(default=0)),
                ('memory_mb', models.IntegerField(default=0)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('docker_version', models.CharField(blank=True, max_length=50)),
                ('openstack_version', models.CharField(blank=True, max_length=50)),
                ('kvm_version', models.CharField(blank=True, max_length=50)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='portal.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('flavor_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('project_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('last_cpu_usage_pct', models.FloatField(default=0.0)),
                ('last_ram_usage_mb', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='portal.physicalhost')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.physicalhost')),
            ],
        ),
    ]
