# Generated by Django 5.0.1 on 2025-11-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='instance',
            name='network_name',
            field=models.CharField(default='provider-net', max_length=100),
        ),
    ]
