# Generated by Django 5.0.1 on 2025-11-29 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_instance_ip_address_instance_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='target_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cluster'),
        ),
        migrations.AddField(
            model_name='physicalhost',
            name='memory_mb_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='physicalhost',
            name='vcpus_used',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClusterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('zone', models.CharField(default='nova', max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='Unknown', max_length=50)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portal.cluster')),
            ],
        ),
    ]
