# Generated by Django 5.0.1 on 2025-11-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alert_target_cluster_physicalhost_memory_mb_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_interval_minutes', models.IntegerField(default=10, help_text='Inventory collection frequency in minutes')),
            ],
        ),
    ]
