# Generated by Django 5.0.1 on 2025-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_appversion_flavor_versionfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='image_name',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='instance',
            name='key_name',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='instance',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
