# Generated by Django 5.0.1 on 2025-11-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_instance_image_name_instance_key_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalhost',
            name='bios_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='physicalhost',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='physicalhost',
            name='hardware_health',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='physicalhost',
            name='idrac_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='physicalhost',
            name='service_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='ome_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='ome_url',
            field=models.URLField(blank=True, help_text='https://ome.example.com', null=True),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='ome_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
