# Generated by Django 5.0.1 on 2025-11-30 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_physicalhost_bios_version_physicalhost_cpu_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size_gb', models.IntegerField()),
                ('device', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('is_bootable', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='portal.instance')),
            ],
        ),
    ]
