# Generated by Django 5.0.1 on 2025-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
