# Generated by Django 5.0.1 on 2025-11-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_cluster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='password',
            field=models.TextField(help_text='Stored encrypted'),
        ),
    ]
