# Generated by Django 5.0.1 on 2025-11-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_cluster_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Dell PowerEdge R740', max_length=100, unique=True)),
                ('monthly_amortization', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly hardware cost (CAPEX/Lease)', max_digits=10)),
                ('average_watts', models.IntegerField(default=300, help_text='Average power consumption in Watts')),
            ],
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='electricity_cost',
            field=models.DecimalField(decimal_places=4, default=0.12, help_text='Cost per kWh', max_digits=6),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='pue',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Power Usage Effectiveness', max_digits=4),
        ),
        migrations.AlterField(
            model_name='portalsettings',
            name='ome_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalhost',
            name='server_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.servercostprofile'),
        ),
    ]
